[workspace]
authors = ["Sylens Wong <qiumin14@163.com>"]
channels = ["conda-forge"]
name = "RenderCV_Pod"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
cv = { cmd = 'rendercv render {{yaml}}', args = ["yaml"], cwd = "."}

[dependencies]
python = "3.12.*"
rust = "*"

[pypi-dependencies]
rendercv = { version = "*", extras = ["full"] }
setuptools = "*"
aider-chat = "*"